### PR TITLE
Let's see if this works?

### PR DESCRIPTION
**Pull request by Jimbodiah**
Changed all the ModIntegrations to remove AFTER and change to FOR, or add FOR if it was not there to begin with.

### CODE REVIEW

**Comment by Jimbodiah** [comment]
HAH. That sure looks cool. Now to hope it works!

I deleted my old fork and created a new one from you dev fork, then made the changes and did the PR.

**Comment by shadowmage45** [comment]
Hehe, with real use of Git -- you could do all of these changes locally, using your favorite text-editor, and then push a single commit that contained all the changes (or even a single push with multiple smaller commits).

**Comment by Jimbodiah** [comment]
Let's not push it :)   If I can get this to work, it might already be a whole lot faster? :)

**Comment by shadowmage45** [comment]
Oh, certainly.  Much faster to merge a single PR than 50+ :)

Small steps...

**Comment by Jimbodiah** [comment]
ROFL...  baby steps :)

**Comment by shadowmage45** [comment]
Indeed, gotta start somewhere :)

The last step on these before I could merge the PR -- have you done any testing to make sure it didn't break anything?  I can't really see those changes doing anything bad, but I've been surprised in the past.

If all is well during testing, I'll see about merging this (and your other PR's) for a possible update this weekend / next weekend (depending on the rest of my schedule).

**Pull request merged**
