### PR TITLE
EPL: Add resources to tanks

### PR DESCRIPTION
**Pull request by Jimbodiah**

### CODE REVIEW

**Comment by shadowmage45** [comment]
Hmm.. it doesn't work with a standard :FOR[SSTU] block?

**Comment by Jimbodiah** [comment]
No idea. What's the difference?

**Comment by shadowmage45** [comment]
One runs with the rest of the SSTU patches (:FOR[SSTU]), the other runs -after- all of the SSTU patches (AFTER[SSTU]), and should only be used when the things it is patching depends on things that were patched in the FOR[SSTU] block.

Basically, with patches that ship with a mod, you should use FOR whenever possible.  Save using 'AFTER' for when you explicitly need to run after some other patch.

**Comment by Jimbodiah** [comment]
I'll try it out, brb.

**Comment by Jimbodiah** [comment]
It works!!   ["Ofcourse it does" Mage thinks, rolling his eyes]

I'll change it and have a look at the other resource patches I added.

**Comment by Jimbodiah** [comment]
I don't see any that use AFTER... but a lot don't have FOR[SSTU] either. Would it be better to add FOR[SSTU] to all of those?   They work on my end as-is, but I can change them to be safe if you like.

**Comment by shadowmage45** [comment]
Generally yes - any patches that are shipped with SSTU should use the :FOR[SSTU] convention.

There _might_ be specific exceptions to this, but I can't think of any with the current patch setup.

**Comment by Jimbodiah** [comment]
I'll do those along with the docking port cfgs then

**Comment by Jimbodiah** [comment]
Get ready for 50 pull requests though

**Comment by shadowmage45** [comment]
Heh, really need to get you using Git proper -- where you can create new branch, and do all of the work on separate parts all in one PR/commit.

For now though -- please just try to target them all at the SSTU-dev branch.  (when they target master, it is a few extra steps I have to do on each PR, and with many PRs, the time starts to add up -- much simpler/faster to just target the right branch from the beginning).

**Comment by Jimbodiah** [comment]
euhm.... let me see if I can find it (already did 3-4 PRs)

How do I do a branch? cq does that work only the web client or do I need the github app?

**Pull request closed without merging**
