### PR TITLE
USI-ART: Add Rock as a resource to MFT

### PR DESCRIPTION
**Pull request by Jimbodiah**

### CODE REVIEW

**Comment by shadowmage45** [comment]
Re:  The USI mod suite --- I'm not sure if the NEEDS blocks will work properly with these mods due to the mod/folder structure.

My previous attempts to have a NEEDS setup for Kontainers is entirely broken due to the fact that there is no Kontainers mod defined.  Many of the other USI mods likely have the same problem; unsure if it impacts ART specifically though.

Have you been able to test this patch both with and without ART installed?

**Comment by Jimbodiah** [comment]
Euhm, not without ART yet to be honest. I will check and get back to you.

**Comment by Jimbodiah** [comment]
I have a clean install with only sstu and the other resources no longer show up in the MFT, so it seems to work.

**Comment by shadowmage45** [comment]
Sounds good to me.  As long as there is no crashing, and no resources showing up when they are otherwise useless, seems like it should work as intended.

**Comment by Jimbodiah** [comment]
USI LS shows up though in the pods ;)

**Comment by shadowmage45** [comment]
They show up even when USI-LS is not installed?

**Comment by Jimbodiah** [comment]
Yes... already checking, maybe they are patched in more than one place.

**Comment by Jimbodiah** [comment]
Close this one?

**Comment by shadowmage45** [comment]
Looks like it can be merged actually.  Might require a few updates later for the more recent parts, but is probably a good starting point.

**Comment by Jimbodiah** [comment]
lol, yeah I think the L tank needs to be replaced with the LV now.

**Pull request merged**
