### PR TITLE
Update SC-GEN-FR-W.cfg

### PR DESCRIPTION
**Pull request by Jimbodiah**
Move to category Aerodynamics

### CODE REVIEW

**Comment by shadowmage45** [comment]
Further examination points out that the Aerodynamics category does not exist -- the proper name is 'Aero' -- the patches as they are will cause KSP to hang-on-load as it cannot locate the specified 'Aerodynamics' category.

Yes... I know.. stock needs to get some common sense and conformity in their naming.

However, the point is -- please test these patches before you submit them.

**Comment by Jimbodiah** [comment]
Hmmmmph... Sorry about that, took it for granted they named it like the category. Assumption... Will check next time, as with the science names.

**Comment by shadowmage45** [comment]
:)

Those are the exact reasons I often leave placeholder values in things -- it takes awhile to dig up what the proper names for things are, as they are not apparent from the in-game names.

Still, thanks, the PRs are much appreciated and save me considerable time.

**Comment by Jimbodiah** [comment]
Glad to help a little. Still finding my way in all the files, as you noticed ;)

**Pull request merged**
