### PR TITLE
MUS: Xe + Ore

### PR DESCRIPTION
**Pull request by Jimbodiah**
Yeah, this one is questionable in regards to Ore. Change at your own discrepancy.

### CODE REVIEW

**Comment by shadowmage45** [comment]
Yeah, I'll have to adjust this a bit; should probably not add Ore or Xenon to the 'support' tank of the MUS (as that is explicitly for its monopropellant/battery).

**Comment by Jimbodiah** [comment]
Didn't know what to do with it... feel free to change/remove.

**Comment by shadowmage45** [comment]
Can leave this one open; I just haven't had time to do the changes/fixes yet :)

Still intend to add those resources (at least Xe) to the MUS main tank.

**Comment by Jimbodiah** [comment]
Ah :)

**Comment by shadowmage45** [comment]
Huh, I didn't know I could edit external PRs myself.

Keeping Xenon in both sub-tanks.  Who knows, perhaps there will be a Xenon RCS option in the future.

Remove Ore.  These are fuel tanks after all, with a specific purpose, not intended for general storage.

Will merge after I get a chance to look things over again; head is still spinning from work.....

**Pull request merged**
