### PR TITLE
EPL update

### PR DESCRIPTION
**Pull request by Jimbodiah**
- Add workshop to COS and DOS modules (calculate productivity using crew capacity)
- Define resources MaterialKits and SpecializedParts
- Add resources to MFT

### CODE REVIEW

**Comment by shadowmage45** [comment]
I'll have to remember to update/adjust my 'optional-patches' setup, as some of this was already handled there. (though, probably should just delete that patch set entirely, and merge in the patches that will 'ship' with SSTU; all the non-destructive stuff)

**Comment by shadowmage45** [comment]
Re:  MaterialKits and SpecializedParts -- those are USI (UKS) specific resources, and should not be used with EPL as a stand-alone mod.  Construction resources need to default to 'RocketParts' for when things are used without USI.  (Unless things have changed in EPL that I haven't caught up on recently?)

This does create a bit of a.... problem though, as there will need to be two/three? different sets of patch files.
1.)  UKS used by itself / without EPL installed.  Needs to use the USI resource chain / ground-construction.
2.)  UKS + EPL installed.  Needs to use the USI resource chain.
3.)  EPL without UKS.  Needs to use the simplified EPL (RocketParts) resource chain.

So perhaps #1&2 can be combined into a single patch for when UKS is present, but certainly there needs to be some exclusions on the stand-alone EPL patch to disable itself when UKS is installed.

----

The workshop bits should be fine though, and I might end up trimming this PR down to just those bits while I figure out how to handle the rest of the messy stuff.

**Comment by Jimbodiah** [comment]
MKS uses MetallicOre, EPL uses MetalOre as an intermediate resource that are basically identical except not the same for some reason. EPL also has ScrapMetal and Metal, outside of MKS.

RP is for EPL but is a standard resource for SSTU, and honestly I removed the MKS patch for EPL because it was a PITA. I had ART installed to mine asteroids, but that mod is broken right now (parts just letting go, kraken and exploding parts issues). Not sure if EPL+MKS should be something SSTU needs to worry about.

EPL: RocketParts, MetalOre, Metal, ScrapMetal
MKS: SpecializedParts, Materialkits, MetallicOre, Substrate, Minerals, Water and probably some more...

For the EPL patch I'd only use those resources. I just copies the wrong patch text into my first PR, listing the MKS replacements instead of the actual EPL resources.

**Comment by Jimbodiah** [comment]
files superceded by other changes... will check if this is still relevant, and make a new PR if needed, or just add to my own patches. Closing for now.

**Comment by shadowmage45** [comment]
Yeah, I noticed this one when I merged the others.  And then went "huh?" when I saw this one... apparently I had missed/forgotten about this PR.

Please let me know / put up a new PR if the changes are still needed.

**Pull request closed without merging**
