### PR TITLE
New vacuum engine Isp curves

### PR DESCRIPTION
**Pull request by MikeOnTea**
New vacuum engine I<sub>sp</sub> curves calculated/estimated with the help of NASAs nozzle simulator. Bottom line I<sub>sp</sub> is 10s, which is used when the engine exit pressure is below 10% of the ambient pressure.
Some I<sub>sp</sub> values slightly changed based on the sources i used for my research of data needed for the simulation. The most notable example/largest change is the AJ10-190, which changed from 330s to 316s (see [Astronautix](http://www.astronautix.com/o/ome.html), [NASA 1](https://ntrs.nasa.gov/archive/nasa/casi.ntrs.nasa.gov/19950002757.pdf) or [NASA 2](https://science.ksc.nasa.gov/shuttle/technology/sts-newsref/sts-oms.html), the latter stating only 313s).

### CODE REVIEW

**Comment by shadowmage45** [comment]
All effected SM parts will need to have their resource-quantities and dry part-mass adjusted to maintain the same dV from the assembled spacecraft.
* SC-C = ~1340
* SC-B = ~2800
* SC-A = ~340m/s with option to fill up tank for ~420m/s
* ICPS/HUS -- parts really need to be removed entirely, I wouldn't bother either patching their ISP, or adjusting their mass/etc.

Why the changes to the SM engines?

I was fully prepared to accept the changes to the vacuum engines (RL10's, J2/X), but the rest is a bit overboard, and results in far more fix-up work for me.

**Comment by MikeOnTea** [comment]
What engines do you mean in particular? The SC-A and SC-C SMs have ~0.6%/~1% _higher_ vacuum I<sub>sp</sub>, the SC-B SM's vacuum I<sub>sp</sub> didn't change, so basically they didn't really change (unless you use them in a kerbin/earth like atmosphere, of course) and thus no fixing/other editing should be needed, unless i'm missing something. If those <=1% buffs are a problem for the SC-A/C SM, i could redo the curves with their previous vacuum I<sub>sp</sub> values, or just undo those changes for them.
The only major nerf was to the (standalone) AJ10-190, as i couldn't find any source for its high I<sub>sp</sub>.

As to why - i figured the upper stage engines were the most important, but i thought i can as well do it for all vacuum engines when i'm at it, if only for consistency reasons.

And no worry, if you're unhappy i can of course make some adjustments, i'm trying to understand the problem though first. :)

**Comment by shadowmage45** [comment]
My apologies, apparently I didn't read through the changed-files list very well.

I thought that the SC-C-CM was changing from 330 -> 316, but I can see that its current stats are only ~315, so not a very big change at all.

Really not sure where that ~330isp came from on the -190.  Possibly a long-standing copy-pasta error that never got caught before now.

----

Would still like to maintain the same vacuum dV out of the SM parts though, so will need to do some examination on those to see just how effected they are from the changes.  I'm okay with it being a bit off (single digits of difference), but if it is more than 8-10dV different, some part-mass adjustments will be needed.

**Comment by MikeOnTea** [comment]
Well, let's check the delta-v numbers for the SC-A/C.
The SC-A (just the 3 parts, without crew) with the old I<sub>sp</sub> and full tank has **389m/s**, this value would increase to **391m/s** (values as reported by KER). I did a quick search and found 390m/s on [Astronautix](http://www.astronautix.com/s/soyuztma.html), so that should be ok, i guess?

The SC-C (just the 2 parts, using the reentry module) would increase from **1368m/s** to **1382m/s**. Having done a quick search, Wikipedia mentions [1800m/s](https://en.wikipedia.org/wiki/Orion_Service_Module), while Astronautix states [1855m/s](http://www.astronautix.com/o/orionsm.html). I found other mentions of 1340m/s, but have no idea why the difference is that big, maybe old/new design numbers?
That said, i have no problem with keeping the old I<sub>sp</sub> of 313s for the SC-C and would be happy to create a curve for it if you like (and probably use that for the AJ10-190 as well!?). The only reason i changed it to 316s was that i did the (standalone) AJ10-190 first and reused that curve for the SC-C.

**Comment by shadowmage45** [comment]
That all sounds reasonable to me.  Will see about doing some testing on it all, and merging it in for the next release.

I'm not readily finding sources on where I got the SC-C-SM's dV values -- pretty sure it was a 'fairly reliable source' at the time (likely a combination of wikipedia, astronautica, and nasa-spacefight-forum posts); I believe the actual ~1340 figure came from plugging in the ~316 ISP along with the mass of the CM and dry+propellant mass for the SM.  I could likely find my calculation spreadsheet somewhere, but they probably don't include any links/references (and even if they did, it is likely that the information in those sources has changed in the interim).

**Comment by shadowmage45** [comment]
Found the source of the ~1340 dV on the SC-C-SM:

https://en.wikipedia.org/wiki/Orion_(spacecraft) -- (same mass listed in many places)
Capsule: 10,387 kg (22,899 lb)
Service module: 15,461 kg (34,086 lb)
Total: 25,848 kg (56,985 lb)

http://www.braeunig.us/space/specs/orion.htm
Orion-SM Stats:
Dry mass: 6,185 kg
Launch mass: 15,461 kg
(assuming all of the difference between 'launch' and 'dry' is the propellant -- likely some of it is pressurant and the fairing side panels)

Plugging those values into the dV equation gives ~1379.5 dV for the spacecraft.

I'm really not seeing how/where people are coming up with the ~1800 number?


This NASA source also states roughly the same stats as I've posted above... after you convert from silly US'ian feet/lbs to kg/meters.
https://www.nasa.gov/sites/default/files/fs-2014-08-004-jsc-orion_quickfacts-web.pdf

And this one is pretty close to the others as well...
https://www.lpi.usra.edu/lunar/constellation/orion/factsheet.pdf

**Comment by shadowmage45** [comment]
Everything is looking good so far, the craft that I've tested that use vacuum engines have had no issues.

Will have to add some notes/warnings to these specific engines that state they only work above certain altitudes, as well as state the specific altitude in the description somewhere.

@MikeOnTea 
Going to merge in the ISP updates as-is, but could perhaps use some assistance on figuring out what the cut-off altitudes are.  I'm sure I would be able to figure it out after some research and calculation, but it looked like you might have had that information already on hand from your curve plots.

**Comment by MikeOnTea** [comment]
Well, to create the curves i only defined a cutoff pressure. To get the altitude plots/I<sub>sp</sub> i used KER and its altitude slider. As i only plotted some engines i only have the altitude cutoff points for those.
I wonder if it's worth to put that much effort into it though, i'd probably just give a common warning like "Vacuum optimized engine, only works in vacuums and low pressure conditions".
That said, the kerbin cutoff altitudes i wrote down are:
RL10A-3: 6.7km
RL10A-4: 7.5km
RL10B-2: 14.4km
J-2X: 4.5km
Merlin 1BV: 2.6km
Merlin 1DV: 7.9km
RD-0110: 4.9km

**Pull request merged**
