### PR TITLE
Expose deployment state to other mods

### PR DESCRIPTION
**Pull request by henrybauer**
This lets other mods (like [SafeChute](https://forum.kerbalspaceprogram.com/index.php?/topic/90954-130-safechute-v217-continued/)) tell whether the parachutes have been deployed.

If there's a better way (besides parsing chutePersistence, which is already public), please let me know

### CODE REVIEW

**Comment by shadowmage45** [comment]
I personally think that a visibility adjustment to this field would accomplish a bit of a cleaner setup:

https://github.com/henrybauer/SSTULabs/blob/434c200a0238e6266343e4175d1f7c6e7f288903/Plugin/SSTUTools/SSTUTools/Module/SSTUModularParachute.cs#L177

Should be able to set that to 'public', and get live access to whatever the actual chute-state is.  Although, that exposes an enum, which are.... difficult... to cope with through reflection.

Will give it some thought -- the cleanest way would be to expose that enum-field, but I think from a reflection-based-interop standpoint, the boolean methods are probably easier to deal with (e.g. what you had proposed).

**Comment by henrybauer** [comment]
Yep, exposing chuteState would also work.  Actually I just saw chutePersistence is already public and keeps the same value as chuteState, but as a string.  No need to expose chuteState and no worries about enums.

The upside to parsing chutePersistence is that there's no code changes needed in SSTU; the downside is that I'll have to keep a list of those state names and make sure they match the current version of SSTU.

How likely are these state names ("MAIN_DEPLOYING_FULL", etc) to change?

**Comment by shadowmage45** [comment]
Sorry for the delayed response.

The enum names are pretty much set in stone.  

Changing enum names = bad, as you never know who has stored the name in a string, and when it would crash due to the change.  If there were ever a change in the enum names it would also come with different PartModules, so there would be larger incompatibilities to worry about at that time.

**Comment by shadowmage45** [comment]
Sounds like you have this covered by parsing the string-based persistence state.  Please let me know if you still need any additional accessor changes.

**Pull request closed without merging**
