### PR TITLE
Resource support for WildBlue DSEV

### PR DESCRIPTION
**Pull request by Jimbodiah**

### CODE REVIEW

**Comment by shadowmage45** [comment]
How does this patch play with the TAC patches that also add defs for 'Water' ?  Are there problems with multiple defs for the same resource?

**Comment by Jimbodiah** [comment]
I've not noticed, but I can make an exception to check for TAC and then skip water on this patch.

**Comment by Jimbodiah** [comment]
Not sure, but I think %resource = water would overwrite the first resource it sees.

**Comment by shadowmage45** [comment]
Yeah, was going to say you could make a TAC exception by moving the water to a separate definition.

Do those mods use the same volume/density/etc for water?  If it is fairly standardized, I would consider moving the volume def/etc into the base SSTU defs.

**Comment by Jimbodiah** [comment]
Don't know, I've not used water for DSEV, I think it's for some kind of mining/conversion resource.

**Comment by Jimbodiah** [comment]
PS: Added the exception to check for the presence of TAC

**Pull request merged**
